// @ts-nocheck
// This file is autogenerated by scripts/build-registry.ts
// Do not edit this file directly.
import * as React from "react"

export const Index: Record<string, any> = {
  "default": {
    "token-card": {
      name: "token-card",
      type: "registry:ui",
      registryDependencies: undefined,
      files: ["registry/default/ui/token-card.tsx"],
      component: React.lazy(() => import("@/registry/default/ui/token-card.tsx")),
      source: "",
      category: "undefined",
      subcategory: "undefined",
      chunks: []
    },
    "token-thumbnail": {
      name: "token-thumbnail",
      type: "registry:ui",
      registryDependencies: undefined,
      files: ["registry/default/ui/token-thumbnail.tsx"],
      component: React.lazy(() => import("@/registry/default/ui/token-thumbnail.tsx")),
      source: "",
      category: "undefined",
      subcategory: "undefined",
      chunks: []
    },
    "token-card-demo": {
      name: "token-card-demo",
      type: "registry:example",
      registryDependencies: ["token-card"],
      files: ["registry/default/example/token-card-demo.tsx"],
      component: React.lazy(() => import("@/registry/default/example/token-card-demo.tsx")),
      source: "",
      category: "undefined",
      subcategory: "undefined",
      chunks: []
    },
    "token-thumbnail-demo": {
      name: "token-thumbnail-demo",
      type: "registry:example",
      registryDependencies: ["token-thumbnail"],
      files: ["registry/default/example/token-thumbnail-demo.tsx"],
      component: React.lazy(() => import("@/registry/default/example/token-thumbnail-demo.tsx")),
      source: "",
      category: "undefined",
      subcategory: "undefined",
      chunks: []
    },
    "utils": {
      name: "utils",
      type: "registry:lib",
      registryDependencies: undefined,
      files: ["registry/default/lib/utils.ts"],
      component: React.lazy(() => import("@/registry/default/lib/utils.ts")),
      source: "",
      category: "undefined",
      subcategory: "undefined",
      chunks: []
    },
    "use-mobile": {
      name: "use-mobile",
      type: "registry:hook",
      registryDependencies: undefined,
      files: ["registry/default/hooks/use-mobile.tsx"],
      component: React.lazy(() => import("@/registry/default/hooks/use-mobile.tsx")),
      source: "",
      category: "undefined",
      subcategory: "undefined",
      chunks: []
    },
    "use-toast": {
      name: "use-toast",
      type: "registry:hook",
      registryDependencies: undefined,
      files: ["registry/default/hooks/use-toast.ts"],
      component: React.lazy(() => import("@/registry/default/hooks/use-toast.ts")),
      source: "",
      category: "undefined",
      subcategory: "undefined",
      chunks: []
    },
  },
}
