name: "frontend CI"

on:
  push:
    paths:
      - "apps/www/**"
  pull_request:
    paths:
      - "apps/www/**"
  workflow_dispatch:

env:
  ALIAS_DOMAIN_PREV: "token-kit.vercel.app"
  ALIAS_DOMAIN_PROD: "token-kit.vercel.app"
  PROJ_PATH: "apps/www"

jobs:
  deploy:
    runs-on: ubuntu-latest
    if: ${{ contains(
      fromJson('["push", "workflow_dispatch"]'),
      github.event_name) &&
      contains(
      fromJson('["main"]'),
      github.ref_name)
      }}
    steps:
      - uses: actions/checkout@v4
      - name: Deploy to Vercel Action
        uses: BetaHuhn/deploy-to-vercel-action@v1
        with:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          VERCEL_TOKEN: ${{ secrets.VERCEL_TOKEN }}
          VERCEL_ORG_ID: ${{ secrets.VERCEL_ORG_ID }}
          VERCEL_PROJECT_ID: ${{ secrets.VERCEL_PROJECT_ID }}
          GITHUB_DEPLOYMENT_ENV: ${{ github.ref_name == 'prod' && 'production' || 'preview' }}
          PRODUCTION: ${{ github.ref_name == 'prod' }}
          ALIAS_DOMAINS: ${{ github.ref_name == 'prod' && env.ALIAS_DOMAIN_PROD || env.ALIAS_DOMAIN_PREV }}
          VERCEL_SCOPE: "smart-token-labs"
